---
# Copyright 2019-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Globally define a namespace and registry
global:
  namespace: voltha
  registry: ''

# Define connectivity to Kafka
kafka:
  adapter:
    service: cord-kafka.default.svc.cluster.local
    port: 9092
  cluster:
    service: cord-kafka.default.svc.cluster.local
    port: 9092

# Define connectivity to etcd
etcd:
  service: etcd-cluster-client.default.svc.cluster.local
  port: 2379

# Define controller to which to connect
controller:
  service: onos-openflow.default.svc.cluster.local
  port: 6653

# WIP Define the number of read/write core pairs
rw_core:
  pairs: 2

# WIP Define the number of read-only core pairs
# (Why are these pairs and not just replicas)
ro_core:
  pairs: 1

# Define the recplica count for everything
replicas:
  vcli: 1
  ofagent: 1
  rw_core: 1
  ro_core: 1
  afrouter: 1
  afrouterd: 1
  adapter_simulated_olt: 1
  adapter_simulated_onu: 1
  onu: 1

node_ports:
  vcli_port: 30110

# Define Docker images to be used
images:
  vcli:
    repository: 'volthacore/voltha-cli'
    tag: '{{ .Chart.AppVersion }}'
    pullPolicy: 'Always'

  ofagent:
    repository: 'volthacore/voltha-ofagent'
    tag: '{{ .Chart.AppVersion }}'
    pullPolicy: 'Always'
 
  ro_core:
    repository: 'volthacore/voltha-ro-core'
    tag: '{{ .Chart.AppVersion }}'
    pullPolicy: 'Always'
 
  rw_core:
    repository: 'volthacore/voltha-rw-core'
    tag: '{{ .Chart.AppVersion }}'
    pullPolicy: 'Always'
 
  afrouter:
    repository: 'volthacore/voltha-afrouter'
    tag: '{{ .Chart.AppVersion }}'
    pullPolicy: 'Always'

  afrouterd:
    repository: 'volthacore/voltha-afrouterd'
    tag: '{{ .Chart.AppVersion }}'
    pullPolicy: 'Always'
    restartPolicy: 'Always'

  adapter_simulated_olt:
    repository: 'volthacore/voltha-adapter-simulated-olt'
    tag: '{{ .Chart.AppVersion }}'
    pullPolicy: 'Always'

  adapter_simulated_onu:
    repository: 'volthacore/voltha-adapter-simulated-onu'
    tag: '{{ .Chart.AppVersion }}'
    pullPolicy: 'Always'

  ponsim:
    repository: 'volthacore/voltha-ponsim'
    tag: '{{ .Chart.AppVersion }}'
    pullPolicy: 'Always'
