apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ofagent
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.replicas.ofagent }}
  template:
    metadata:
      labels:
        app: ofagent
      annotations:
        cni: "calico"
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: ofagent
        image: {{ .Values.global.registry }}{{ .Values.images.ofagent.repository }}:{{ tpl .Values.images.ofagent.tag . }}
        imagePullPolicy: {{ .Values.images.ofagent.pullPolicy }}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        args:
        - "/ofagent/ofagent/main.py"
        - "-v"
        - "--consul=consul.$(NAMESPACE).svc.cluster.local:8500"
        - "--controller=onos.$(NAMESPACE).svc.cluster.local:6653"
        - "--grpc-endpoint=afrouter.$(NAMESPACE).svc.cluster.local:55555"
        - "--enable-tls"
        - "--key-file=/ofagent/pki/voltha.key"
        - "--cert-file=/ofagent/pki/voltha.crt"
