# Copyright 2019-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ofagent
  serviceAccountName: {{ .Values.serviceaccount }}
spec:
  replicas: {{ .Values.replicas.ofagent }}
  template:
    metadata:
      labels:
        app: ofagent
      annotations:
        cni: "calico"
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccountName: {{ .Values.serviceaccount }}
      containers:
      - name: ofagent
        image: {{ .Values.registry }}{{ .Values.images.ofagent.repository }}:{{ tpl .Values.images.ofagent.tag . }}
        imagePullPolicy: {{ .Values.images.ofagent.pullPolicy }}
        env:
        - name: CONTROLLER_SERVICE
          value: "{{ .Values.services.controller.service }}:{{ .Values.services.controller.port }}"
        args:
        - "/ofagent/ofagent/main.py"
        - "-v"
        - "--controller=$(CONTROLLER_SERVICE)"
        - "--grpc-endpoint=voltha-api.{{ .Release.Namespace }}.svc.cluster.local:55555"
