# Copyright 2019 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rw-core1
  namespace: {{ .Values.global.namespace }}
  serviceAccountName: {{ .Values.global.namespace }}-serviceaccount
spec:
  replicas: {{ .Values.replicas.rw_core }}
  selector:
    matchLabels:
      app: rw-core
  template:
    metadata:
      labels:
        app: rw-core
      annotations:
        cni: "calico"
    spec:
      namespace: {{ .Values.global.namespace }}
      serviceAccountName: {{ .Values.global.namespace }}-serviceaccount
      containers:
        - name: voltha
          image: {{ .Values.global.registry }}{{ .Values.images.rw_core.repository }}:{{ tpl .Values.images.rw_core.tag . }}
          imagePullPolicy: {{ .Values.images.rw_core.pullPolicy }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ETCD_SERVICE
              value: "{{ .Values.etcd.service }}"
            - name: ETCD_SERVICE_PORT
              value: "{{ .Values.etcd.port }}"
            - name: ADAPTER_KAFKA_SERVICE
              value: "{{ .Values.kafka.adapter.service }}"
            - name: ADAPTER_KAFKA_SERVICE_PORT
              value: "{{ .Values.kafka.adapter.port }}"
            - name: CLUSTER_KAFKA_SERVICE
              value: "{{ .Values.kafka.cluster.service }}"
            - name: CLUSTER_KAFKA_SERVICE_PORT
              value: "{{ .Values.kafka.cluster.port }}"
          args:
            - "/app/rw_core"
            - "-instance-id=rw-core1"
            - "-kv_store_type=etcd"
            - "-kv_store_host=$(ETCD_SERVICE)"
            - "-kv_store_port=$(ETCD_SERVICE_PORT)"
            - "-grpc_host=$(POD_IP)"
            - "-grpc_port=50057"
            - "-banner=true"
            - "-kafka_adapter_host=$(ADAPTER_KAFKA_SERVICE)"
            - "-kafka_adapter_port=$(ADAPTER_KAFKA_SERVICE_PORT)"
            - "-kafka_cluster_host=$(CLUSTER_KAFKA_SERVICE)"
            - "-kafka_cluster_port=$(CLUSTER_KAFKA_SERVICE_PORT)"
            - "-rw_core_topic=rwcore"
            - "-kv_store_data_prefix=service/voltha"
            - "-in_competing_mode=true"
            - "-timeout_long_request=8000"
            - "-timeout_request=6000"
            - "-log_level=4"
          ports:
            - containerPort: 50057
              name: grpc-port
      nodeSelector:
        nodename: compute1



